/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    capabilities: Capability;
    industries: Industry;
    'impact-stories': ImpactStory;
    insights: Insight;
    faqs: Faq;
    'team-members': TeamMember;
    careers: Career;
    partners: Partner;
    testimonials: Testimonial;
    resources: Resource;
    enquiries: Enquiry;
    'newsletter-subscribers': NewsletterSubscriber;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'impact-stories': ImpactStoriesSelect<false> | ImpactStoriesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    'coe-page': CoePage;
    'governance-page': GovernancePage;
    'company-page': CompanyPage;
    'contact-page': ContactPage;
    'privacy-policy': PrivacyPolicy;
    'terms-of-use': TermsOfUse;
    'responsible-ai': ResponsibleAi;
    'cookie-policy': CookiePolicy;
    'accessibility-statement': AccessibilityStatement;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'coe-page': CoePageSelect<false> | CoePageSelect<true>;
    'governance-page': GovernancePageSelect<false> | GovernancePageSelect<true>;
    'company-page': CompanyPageSelect<false> | CompanyPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'terms-of-use': TermsOfUseSelect<false> | TermsOfUseSelect<true>;
    'responsible-ai': ResponsibleAiSelect<false> | ResponsibleAiSelect<true>;
    'cookie-policy': CookiePolicySelect<false> | CookiePolicySelect<true>;
    'accessibility-statement': AccessibilityStatementSelect<false> | AccessibilityStatementSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role:
    | 'super_admin'
    | 'administrator'
    | 'editor'
    | 'reviewer'
    | 'publisher'
    | 'enquiry_manager'
    | 'media_manager'
    | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Required for accessibility on images.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  shortDescription: string;
  valueProposition?: string | null;
  businessProblem?: string | null;
  solutionOverview?: string | null;
  industries?: string[] | null;
  technologies?: string[] | null;
  targetUsers?: string[] | null;
  capabilities?: string[] | null;
  outcomes?: string[] | null;
  dataSources?: string[] | null;
  aiCapabilities?: string[] | null;
  governance?: string[] | null;
  architecture?: string[] | null;
  deploymentOptions?: string[] | null;
  relatedCapabilities?: string[] | null;
  modules?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  workflow?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  productStatus?: string | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: string;
  slug: string;
  name: string;
  shortName?: string | null;
  icon?: string | null;
  summary: string;
  description?: string | null;
  businessChallenge?: string | null;
  deliverables?: string[] | null;
  engagementActivities?: string[] | null;
  typicalDeliverables?: string[] | null;
  useCases?: string[] | null;
  outcomes?: string[] | null;
  relatedProducts?: string[] | null;
  topics?: string[] | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string;
  slug: string;
  name: string;
  summary: string;
  challenges?: string[] | null;
  opportunities?: string[] | null;
  capabilities?: string[] | null;
  products?: string[] | null;
  governance?: string[] | null;
  outcomes?: string[] | null;
  workflows?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stories".
 */
export interface ImpactStory {
  id: string;
  slug: string;
  title: string;
  clientLabel: string;
  industry: string;
  capability?: string | null;
  solutionType?: string | null;
  outcomeCategory?: string | null;
  challenge?: string | null;
  context?: string | null;
  approach?: string | null;
  architecture?: string | null;
  governance?: string | null;
  outcomes?: string[] | null;
  relatedProducts?: string[] | null;
  relatedCapabilities?: string[] | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category?: string | null;
  type?: string | null;
  author?: string | null;
  readingTime?: string | null;
  featured?: boolean | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Plain paragraphs used by the public site and seed import.
   */
  bodyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  placement?: ('contact' | 'coe' | 'governance' | 'products' | 'company' | 'general')[] | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Publish only verified people. Do not invent leadership biographies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  slug: string;
  name: string;
  title?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  order?: number | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Only list roles approved for public posting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string;
  slug: string;
  title: string;
  location?: string | null;
  employmentType?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Publish only when agreements allow public reference.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  slug: string;
  name: string;
  summary?: string | null;
  website?: string | null;
  logo?: (string | null) | Media;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  attribution?: string | null;
  organisation?: string | null;
  role?: string | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  slug: string;
  title: string;
  description?: string | null;
  file: string | Media;
  category?: string | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  type: 'contact' | 'demo' | 'consultation' | 'career';
  status?: ('new' | 'in_progress' | 'waiting' | 'closed' | 'spam') | null;
  reference?: string | null;
  fullName: string;
  workEmail: string;
  phone?: string | null;
  organisation?: string | null;
  designation?: string | null;
  country?: string | null;
  areaOfInterest?: string | null;
  projectSummary?: string | null;
  preferredContactMethod?: string | null;
  product?: string | null;
  capability?: string | null;
  careerRole?: string | null;
  assignee?: (string | null) | User;
  notes?:
    | {
        body: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  email: string;
  status?: ('active' | 'unsubscribed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  action: string;
  collectionSlug?: string | null;
  documentId?: string | null;
  summary: string;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actor?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: string | Capability;
      } | null)
    | ({
        relationTo: 'industries';
        value: string | Industry;
      } | null)
    | ({
        relationTo: 'impact-stories';
        value: string | ImpactStory;
      } | null)
    | ({
        relationTo: 'insights';
        value: string | Insight;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'careers';
        value: string | Career;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  category?: T;
  shortDescription?: T;
  valueProposition?: T;
  businessProblem?: T;
  solutionOverview?: T;
  industries?: T;
  technologies?: T;
  targetUsers?: T;
  capabilities?: T;
  outcomes?: T;
  dataSources?: T;
  aiCapabilities?: T;
  governance?: T;
  architecture?: T;
  deploymentOptions?: T;
  relatedCapabilities?: T;
  modules?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  workflow?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  featured?: T;
  productStatus?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  icon?: T;
  summary?: T;
  description?: T;
  businessChallenge?: T;
  deliverables?: T;
  engagementActivities?: T;
  typicalDeliverables?: T;
  useCases?: T;
  outcomes?: T;
  relatedProducts?: T;
  topics?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  summary?: T;
  challenges?: T;
  opportunities?: T;
  capabilities?: T;
  products?: T;
  governance?: T;
  outcomes?: T;
  workflows?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stories_select".
 */
export interface ImpactStoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  clientLabel?: T;
  industry?: T;
  capability?: T;
  solutionType?: T;
  outcomeCategory?: T;
  challenge?: T;
  context?: T;
  approach?: T;
  architecture?: T;
  governance?: T;
  outcomes?: T;
  relatedProducts?: T;
  relatedCapabilities?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  category?: T;
  type?: T;
  author?: T;
  readingTime?: T;
  featured?: T;
  body?: T;
  bodyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  placement?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  location?: T;
  employmentType?: T;
  summary?: T;
  description?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  summary?: T;
  website?: T;
  logo?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  organisation?: T;
  role?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  file?: T;
  category?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  reference?: T;
  fullName?: T;
  workEmail?: T;
  phone?: T;
  organisation?: T;
  designation?: T;
  country?: T;
  areaOfInterest?: T;
  projectSummary?: T;
  preferredContactMethod?: T;
  product?: T;
  capability?: T;
  careerRole?: T;
  assignee?: T;
  notes?:
    | T
    | {
        body?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  summary?: T;
  meta?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  name: string;
  shortName?: string | null;
  websiteUrl: string;
  description?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?: {
    linkedin?: string | null;
    youtube?: string | null;
    instagram?: string | null;
    x?: string | null;
  };
  seoDefaults?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  announcement?: {
    enabled?: boolean | null;
    message?: string | null;
    href?: string | null;
  };
  cookie?: {
    title?: string | null;
    description?: string | null;
  };
  brandCopy?: {
    headline?: string | null;
    supporting?: string | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  main?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  capabilityNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerCapabilities?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerExplore?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerContact?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLegal?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  capabilityRibbon?: string[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero?: {
    eyebrow?: string | null;
    headlineLine1?: string | null;
    headlineLine2?: string | null;
    supporting?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    trustLine?: string | null;
  };
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Approved section theme only — brand system stays in code.
             */
            sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
            /**
             * Maps to Motion presets. No custom timelines.
             */
            animationPreset?:
              | (
                  | 'none'
                  | 'fade'
                  | 'fade_up'
                  | 'stagger'
                  | 'slide_left'
                  | 'slide_right'
                  | 'mask_reveal'
                  | 'subtle_parallax'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            cards?:
              | {
                  title: string;
                  body?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            title?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            metrics?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Must remain illustrative unless verified.
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metricStrip';
          }
        | {
            title?: string | null;
            description?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            insights?: (string | Insight)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightList';
          }
        | {
            title?: string | null;
            body?: string | null;
            media?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFeature';
          }
      )[]
    | null;
  /**
   * Approved section theme only — brand system stays in code.
   */
  sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
  /**
   * Maps to Motion presets. No custom timelines.
   */
  animationPreset?:
    ('none' | 'fade' | 'fade_up' | 'stagger' | 'slide_left' | 'slide_right' | 'mask_reveal' | 'subtle_parallax') | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe-page".
 */
export interface CoePage {
  id: string;
  title?: string | null;
  description?: string | null;
  /**
   * Migrated structured CoE page content.
   */
  contentJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Approved section theme only — brand system stays in code.
             */
            sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
            /**
             * Maps to Motion presets. No custom timelines.
             */
            animationPreset?:
              | (
                  | 'none'
                  | 'fade'
                  | 'fade_up'
                  | 'stagger'
                  | 'slide_left'
                  | 'slide_right'
                  | 'mask_reveal'
                  | 'subtle_parallax'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            cards?:
              | {
                  title: string;
                  body?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            title?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            metrics?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Must remain illustrative unless verified.
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metricStrip';
          }
        | {
            title?: string | null;
            description?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            insights?: (string | Insight)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightList';
          }
        | {
            title?: string | null;
            body?: string | null;
            media?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFeature';
          }
      )[]
    | null;
  /**
   * Approved section theme only — brand system stays in code.
   */
  sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
  /**
   * Maps to Motion presets. No custom timelines.
   */
  animationPreset?:
    ('none' | 'fade' | 'fade_up' | 'stagger' | 'slide_left' | 'slide_right' | 'mask_reveal' | 'subtle_parallax') | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance-page".
 */
export interface GovernancePage {
  id: string;
  title?: string | null;
  description?: string | null;
  contentJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Approved section theme only — brand system stays in code.
             */
            sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
            /**
             * Maps to Motion presets. No custom timelines.
             */
            animationPreset?:
              | (
                  | 'none'
                  | 'fade'
                  | 'fade_up'
                  | 'stagger'
                  | 'slide_left'
                  | 'slide_right'
                  | 'mask_reveal'
                  | 'subtle_parallax'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            cards?:
              | {
                  title: string;
                  body?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            title?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            metrics?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Must remain illustrative unless verified.
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metricStrip';
          }
        | {
            title?: string | null;
            description?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            insights?: (string | Insight)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightList';
          }
        | {
            title?: string | null;
            body?: string | null;
            media?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFeature';
          }
      )[]
    | null;
  /**
   * Approved section theme only — brand system stays in code.
   */
  sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
  /**
   * Maps to Motion presets. No custom timelines.
   */
  animationPreset?:
    ('none' | 'fade' | 'fade_up' | 'stagger' | 'slide_left' | 'slide_right' | 'mask_reveal' | 'subtle_parallax') | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-page".
 */
export interface CompanyPage {
  id: string;
  vision?: string | null;
  mission?: string | null;
  introduction?: string | null;
  whyAgrayian?: string[] | null;
  deliveryPhilosophy?: string[] | null;
  responsibleAiCommitment?: string | null;
  technologyPhilosophy?: string | null;
  careersCopy?: string | null;
  partnerEcosystemCopy?: string | null;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            /**
             * Approved section theme only — brand system stays in code.
             */
            sectionTheme?: ('dark' | 'light' | 'brand_gradient' | 'technical_grid' | 'minimal') | null;
            /**
             * Maps to Motion presets. No custom timelines.
             */
            animationPreset?:
              | (
                  | 'none'
                  | 'fade'
                  | 'fade_up'
                  | 'stagger'
                  | 'slide_left'
                  | 'slide_right'
                  | 'mask_reveal'
                  | 'subtle_parallax'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            description?: string | null;
            cards?:
              | {
                  title: string;
                  body?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            title?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            metrics?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Must remain illustrative unless verified.
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metricStrip';
          }
        | {
            title?: string | null;
            description?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            insights?: (string | Insight)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightList';
          }
        | {
            title?: string | null;
            body?: string | null;
            media?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFeature';
          }
      )[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  title?: string | null;
  description?: string | null;
  enquiryThemes?: string[] | null;
  consultationFlow?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (string | Faq)[] | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: string;
  title: string;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-use".
 */
export interface TermsOfUse {
  id: string;
  title: string;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "responsible-ai".
 */
export interface ResponsibleAi {
  id: string;
  title: string;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy".
 */
export interface CookiePolicy {
  id: string;
  title: string;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessibility-statement".
 */
export interface AccessibilityStatement {
  id: string;
  title: string;
  description?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * When set in the future, a secured cron can promote to published.
   */
  scheduledPublishAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  websiteUrl?: T;
  description?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        linkedin?: T;
        youtube?: T;
        instagram?: T;
        x?: T;
      };
  seoDefaults?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        message?: T;
        href?: T;
      };
  cookie?:
    | T
    | {
        title?: T;
        description?: T;
      };
  brandCopy?:
    | T
    | {
        headline?: T;
        supporting?: T;
        primaryCta?: T;
        secondaryCta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  main?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  capabilityNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerCapabilities?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerExplore?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerContact?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLegal?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  capabilityRibbon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        supporting?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        trustLine?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              sectionTheme?: T;
              animationPreset?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              title?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metricStrip?:
          | T
          | {
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              description?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        insightList?:
          | T
          | {
              title?: T;
              insights?: T;
              id?: T;
              blockName?: T;
            };
        mediaFeature?:
          | T
          | {
              title?: T;
              body?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
      };
  sectionTheme?: T;
  animationPreset?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coe-page_select".
 */
export interface CoePageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  contentJson?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              sectionTheme?: T;
              animationPreset?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              title?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metricStrip?:
          | T
          | {
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              description?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        insightList?:
          | T
          | {
              title?: T;
              insights?: T;
              id?: T;
              blockName?: T;
            };
        mediaFeature?:
          | T
          | {
              title?: T;
              body?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
      };
  sectionTheme?: T;
  animationPreset?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance-page_select".
 */
export interface GovernancePageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  contentJson?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              sectionTheme?: T;
              animationPreset?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              title?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metricStrip?:
          | T
          | {
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              description?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        insightList?:
          | T
          | {
              title?: T;
              insights?: T;
              id?: T;
              blockName?: T;
            };
        mediaFeature?:
          | T
          | {
              title?: T;
              body?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
      };
  sectionTheme?: T;
  animationPreset?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-page_select".
 */
export interface CompanyPageSelect<T extends boolean = true> {
  vision?: T;
  mission?: T;
  introduction?: T;
  whyAgrayian?: T;
  deliveryPhilosophy?: T;
  responsibleAiCommitment?: T;
  technologyPhilosophy?: T;
  careersCopy?: T;
  partnerEcosystemCopy?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              sectionTheme?: T;
              animationPreset?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              title?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metricStrip?:
          | T
          | {
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              description?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        insightList?:
          | T
          | {
              title?: T;
              insights?: T;
              id?: T;
              blockName?: T;
            };
        mediaFeature?:
          | T
          | {
              title?: T;
              body?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  enquiryThemes?: T;
  consultationFlow?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?: T;
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-of-use_select".
 */
export interface TermsOfUseSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "responsible-ai_select".
 */
export interface ResponsibleAiSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessibility-statement_select".
 */
export interface AccessibilityStatementSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  body?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  scheduledPublishAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}